{
 "title": "Aggregate info",
 "time": { "from": "now-5h", "to": "now-4h" },
 "panels": [
  { "title": "GENERAL INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aggregate Power",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"mybucket\")\r\n  |> range(start: 0, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Aggregate\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Aggregate Power - Graph",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 17, "x": 6, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Dishwasher\" or r[\"_field\"] == \"Aggregate\" or r[\"_field\"] == \"TumbleDryer\" or r[\"_field\"] == \"WashingMachine\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Last Time Fetched",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r._field == \"Aggregate\")\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> map(fn: (r) => ({ r with _value: string(v: r._time) }))\r\n"
    }
   ]
  },
  {
   "title": "PREDICTIONS AND ACTUAL APPLIANCE'S USE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "True Power Dishwasher [W]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Dishwasher\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Predictions state Dishwasher [On/Off]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"Dishwasher\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "Prob state Dishwasher [W]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prob\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"Dishwasher\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "True Power Washing Machine [W]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"WashingMachine\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Predictions state Washing Machine [On/Off]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"WashingMachine\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "Prob state Washing Machine[W]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prob\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"WashingMachine\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "True Power Tumble Dryer [W]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TumbleDryer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Predictions state Tumble Dryer [On/Off]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"TumbleDryer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "Prob state Tumble Dryer",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prob\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"TumbleDryer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "PREDICTIONS AND ACTUAL APPLIANCE'S USE – PARTIAL FIT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "True Power Dishwasher [W]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Dishwasher\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Predictions state Dishwasher [On/Off]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state_helped\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"Dishwasher\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Prob state Dishwasher [W]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state_helped\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prob\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"Dishwasher\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "True Power Washing Machine [W]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"WashingMachine\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Predictions state Washing Machine [On/Off]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state_helped\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"WashingMachine\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Prob state Washing Machine[W]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state_helped\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prob\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"WashingMachine\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "True Power Tumble Dryer [W]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power_monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TumbleDryer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Predictions state Tumble Dryer [On/Off]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state_helped\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"TumbleDryer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Prob state Tumble Dryer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"appliance_state_helped\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"prob\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"TumbleDryer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}